### PR TITLE
Change Jakarta annotation attribute map generation

### PR DESCRIPTION
**Pull request by rbygrave**
- Maps the jakarta key to avaje key
- Suppresses defaults for payload and groups

### CODE REVIEW

**Comment by SentryMan** [comment]
Don't forget java validation

**Comment by rbygrave** [comment]
> Don't forget javax validation

Ha ha, I already have :) ... opps

**Comment by SentryMan** [comment]
Also since we have suppressed payload and groups, we have way to use those, shall I remove from the avaje constraint annotations?

**Comment by SentryMan** [comment]
Ah wait, misread those

**Pull request merged**
