### PR TITLE
Generation part 2

### PR DESCRIPTION
**Pull request by SentryMan**
- fix generator failing when Jakarta/Javax isn't on cp
- add Pattern Constraint
- add Pattern Prism for generation
- fix formatting of generated class constructors

Requires Avaje Prisms 1.9 to be deployed

### CODE REVIEW

**Comment by rbygrave** [comment]
I forgot to release prisms 1.9 ... done that now, heading to central.  Let me know when you are good to merge it.

**Comment by SentryMan** [comment]
@rbygrave should be good to merge now

**Comment by SentryMan** [comment]
I spoke too soon

**Comment by SentryMan** [comment]
There we go, you can merge now

**Pull request merged**
