### PR TITLE
Write to different services path

### PR DESCRIPTION
**Pull request by SentryMan**
relies on https://github.com/avaje/avaje-spi-service/pull/25 to register META-INF services

### CODE REVIEW

**Comment by rbygrave** [comment]
Hmmm, it seems to me with this PR the validation-generator AP using generated-services will then clash with the avaje-spi-service AP? I'm missing something ...

**Comment by SentryMan** [comment]
it's illegal to _write_ to the same file twice, but _reading_ has no such problem

**Comment by SentryMan** [comment]
so what's happening here is that validator is writing to `META-INF/generated-services/ValidatorExtension`. Avaje spi does only read operations on the `META-INF/generated-services` folder, so spi is free to write to `META-INF/services/ValidatorExtension` as no other processor contests that file

**Comment by rbygrave** [comment]
So the avaje-validation-generator has a **_hard dependency_** on avaje-spi-core (annotation processor).

So it has gone from letting avaje-spi-core validate the module-info to being a hard dependency required by the avaje-validation-generator.

**Comment by rbygrave** [comment]
What we get avaje-spi-core to do is merge multiple implementations of a SPI interface in the appropriate META-INF/service file.

It does look like the implication is that **_IF_** an application desires explicit control over the META-INF/service file then they need to disable the `avaje-spi-core` AP. The reason this has got a lot more "interesting" is because in terms of META-INF/service files we now need a lot more "merging" of contents in those files due to adopting the pattern of common spi interfaces when previously we were unlikely to have a clash. That is, previously people could define spi service implementations manually/traditionally if they desired. 

That is, as a consequence of adopting the pattern of common spi interfaces is that we now are MUCH more likely to need content merging those META-INF/services files (in fact maybe this is now really common). IF people are willing to use avaje-spi-service then it can do that merging for us - effectively merging in the contents from META-INF/generated-services files to output into META-INF/services the merged list of services.

**_IF_** the use of avaje-spi-service `@Service` `@ServiceProvider` doesn't work for people and they need to control this explicitly themselves, then they need to disable the `avaje-spi-core` AP.

**Comment by SentryMan** [comment]
> META-INF/service file then they need to disable the avaje-spi-core AP.

You misunderstand, since user defined services are in a different directory(src/main instead of target it is also exempt, and not affected.

**Comment by SentryMan** [comment]
> So the avaje-validation-generator has a hard dependency

You got me there though, I can change this pr to only take effect when avaje spi is detected

**Comment by SentryMan** [comment]
> EDIT: wait a second...

Ok, so I'm still correct, there is still no contention because resources are copied from src/main/resources to target before compilation. (the copy doesn't count as a write) The only thing now is that spi seems to have lost the ability to pick up and validate manual spi interfaces, so gotta fix that

**Pull request merged**
