### PR TITLE
Generate a _type attribute with the target class for min, max, range etc

### PR DESCRIPTION
**Pull request by rbygrave**
We are especially interested in the target types of numbers and datetime types if we want to simplify or optimise the min, max, range, size etc adapters as they can be created knowning the specific type that is being validated.

_For example:_

The extra `_type` attributes here with `int.class` and `long.class`

```java
  public ARangeValidationAdapter(ValidationContext ctx) {
    this.anIntValValidationAdapter = 
        ctx.<Integer>adapter(Range.class, Map.of("min",1L, "max",3L, "message","{avaje.Range.message}", "_type",int.class));

    this.aLongValValidationAdapter = 
        ctx.<Long>adapter(Range.class, Map.of("min",1L, "max",3L, "message","{avaje.Range.message}", "_type",long.class));

  }
```

### CODE REVIEW

**Review by SentryMan — APPROVED** [review]
I think switch is cooler, but LGTM.

**Comment by SentryMan** [comment]
Though hmm, I would like to see at least one test for list/map cases

**Comment by rbygrave** [comment]
I have the thought of translating the Class into a "well known String" and put that into `_type` instead. With the String values we can then use switch. 


int.class | Integer.class -> "Integer"
long.class | Long.class -> "Long"
...
BigDecimal.class -> "BigDecimal"
CharacterSequence | String.class -> "String"

... and if it isn't one of these known types leave it out. So not populating _type for List & Map etc.

**Comment by SentryMan** [comment]
not sure if I'm visualizing this correctly, as part of this may you modify either the time/number adapters to show what you mean?

**Comment by SentryMan** [comment]
I also have a question about runtime checks, suppose somebody creates something like this:

```
record TimeKeeper(@Past Temporal time)
```

for validating whether any of the java.time classes are in the past. We'd still need to check the actual type at runtime to do the validation no?

**Comment by SentryMan** [comment]
Can't say I like the number of adapters we'll have to add, so I guess my real question is whether using the pattern-matching switch from JDK21 is not enough to optimize the instanceof checks.

**Comment by rob-bygrave** [comment]
> the number of adapters we'll have to add

Yup. Far from ideal.

> whether using the pattern-matching switch from JDK21 is not enough to optimize the instanceof checks

Or base a switch on the _type String, I wonder what that would look like ...

**Comment by rob-bygrave** [comment]
More like:

```java
    MaxKnownTypes(AdapterCreateRequest request) {
      super(request);
      this.targetType = request.targetType();
      final var attributes = request.attributes();
      this.value = (long) attributes.get("value");
    }

    @Override
    public boolean isValid(Number number) {
      // null values are valid
      if (number == null) {
        return true;
      }
      return switch (targetType) {
        case "Integer", "Long", "Short", "Byte" -> number.longValue() <= value;
        case "Double" -> compareDouble(number.doubleValue(), value, GREATER_THAN)  <= 0;
        case "Float" -> compareFloat((Float)number, value, GREATER_THAN)  <= 0;
        default -> throw new IllegalStateException();
      };
    }
```

**Review by SentryMan — APPROVED** [review]
still wanna do the pattern-matching switch, but I can work with this.

**Pull request merged**
