### PR TITLE
use basic message interpolator

### PR DESCRIPTION
**Pull request by SentryMan**

### CODE REVIEW

**Comment by SentryMan** [comment]
perhaps we're overthinking this interpolation stuff. I mean having the basic `{}` interpolation should be fine in most cases, especially when users are providing their own messages.

**Comment by rbygrave** [comment]
I need to review the tests etc.  This wasn't quite the "next step" I had in mind, I might be missing the point but message() all gets replaced with message2() and then that is renamed ...

**Comment by SentryMan** [comment]
The point here is to have the message interpolation be done through the dedicated class

**Comment by SentryMan** [comment]
@rbygrave I've changed it for al adapters to use message2

**Comment by rbygrave** [comment]
> @rbygrave I've changed it for al adapters to use message2

Ok. I've been adding tests for each validator as I go for both EN and DE locales.  I'll carry on with that, I don't see those tests in this PR. That is, in a "test driven" type approach I'm first looking to getting working tests for all default messages in EN and DE. Then after that look at the other scenarios which are: custom messages, and only using one locale, messages with the validationValue etc.  So that is the path I'm looking to take. I'll complete my PR and obviously we then have merge conflicts to work through.

**Comment by SentryMan** [comment]
idk, that seems more like testing the adapters proper, rather than testing the message interpolation system to me.

**Comment by rbygrave** [comment]
> testing the message interpolation system to me.

The error message for Size includes the min and max. Many of the other default validation messages are just locale specific literals and no actual interpolation is occurring.

However, one of the things that say Hibernate validator does is support expression language in the validation messages like:

```
must be less than ${inclusive == true ? 'or equal to ' : ''}{value}
```
... and we see that for `DecimalMax` and `DecimalMin` and I'm definitely keen to **not** follow that same path but instead splitting that into 2 messages based on if `inclusive` is true. That is, aiming for pretty dumb simple message interpolation.

So `DecimalMax` and `DecimalMin` are currently problematic and tests if we had them would show that. I am looking to do something there to simplify that around `inclusive` - and I'm doing that in a test driven way.  Once we get past those 2 cases there are some other details that will pop up. 

Additionally noting that **when** the message interpolation actually happens will get interesting because we can do interpolation once and early when only 1 locale is supported and the message doesn't contain `{validatedValue}`.

Plus support for custom resource bundles and custom validation components with their own supplied resource bundles.

**Comment by SentryMan** [comment]
so my initial thought for this would be to have a more generic default message for Size/DecimalMax and let people make custom messages to sort it out instead of trying to remake hibernate's expression language. 

Or else we can make a special exception for the built-in default messages and do a string replace `less than` with `less than or equal to`.

**Pull request closed without merging**
